apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ps-jx
    provider: github
    repository: test-domain
  name: ps-jx-test-domain
spec:
  description: Imported application for ps-jx/test-domain
  httpCloneURL: https://github.com/ps-jx/test-domain.git
  org: ps-jx
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test-domain
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ps-jx/test-domain.git
